<?php
//Help function
function start_members_help($path, $arg) {
	
	$output = '';
	
	switch ($path){
	
		case "admin/help#start_members":
			
			$output = '<p>'. t("Help side for start members") .'</p>';
			
			break;
	
	} 
	
	return $output;
	
}// function start_members_help

//Set perimissions
function start_members_perm() {

	return array('Access Start Members');
	
} // function start_members_perm()

//define block
function start_members_block($op = 'list', $delta = 0, $edit = array()){

	//Define blocks
	if ($op == "list"){
		
		$block = array();
		$block[0]["info"] = t("Memberlist Block");
	}

}