<?php

//Globals
global $_domain;

//Help function
function start_members_help($path, $arg) {
	
	$output = '';
	
	switch ($path){
	
		case "admin/help#start_members":
			
			$output = '<p>'. t("Help side for start members") .'</p>';
			
			break;
	
	} 
	
	return $output;
	
}// function start_members_help

//Set perimissions
function start_members_perm() {

	return array('access start members');
	
} // function start_members_perm()

//define block
function start_members_block($op = 'list', $delta = 0, $edit = array()){

	//Define blocks
	if ($op == "list"){
		
		$block = array();
		$block[0]["info"] = t("Memberlist Block");
	}

}//function _block

//define page
function start_members_all(){

	//init content
	$page_content = '';
	$page_content .= dpm($_domain);
	
	//query to get all users
	$q = db_query('
					SELECT name
					FROM {users}
				');
	
	
	//Loop and add to page_content
	while ($user = db_fetch_array($q)){
		
		$page_content .= "$user[name]<br />";
	}
	
	return $page_content;
}//_all()

//Menu links
function start_members_menu(){
	
	$items = array();
	
	//all page
	$items['start_members'] = array(
		'title' 			=> 'Start members',
		'page callback' 	=> 'start_members_all',
		'access arguments' 	=> array('access start members'),
		'type'				=> MENU_CALLBACK
	);
	
	return $items;
}
